# Generated by Django 3.1.7 on 2021-06-17 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
            ],
            options={
                'verbose_name': 'Level 2',
                'verbose_name_plural': 'Level 2',
            },
        ),
        migrations.CreateModel(
            name='CategoryMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(allow_unicode=True, max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Level 1',
                'verbose_name_plural': 'Level 1',
            },
        ),
        migrations.CreateModel(
            name='CategoryChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
            options={
                'verbose_name': 'Level 3',
                'verbose_name_plural': 'Level 3',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='category_main',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.categorymain'),
        ),
    ]
