# Generated by Django 3.1.7 on 2021-06-19 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_main',
        ),
        migrations.DeleteModel(
            name='CategoryChild',
        ),
        migrations.DeleteModel(
            name='CategoryMain',
        ),
    ]
